config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :users

  get'graphs/volume'
  get'graphs/rep_ranges'
  get'graphs/intensity'

  get'meals/slides'


  resources :workouts
  resources :meals
  resources :journals



  root to: 'users#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :movement


end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user, optional: true
  validates :title, presence: true
  validates :entry, presence: true
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  validates :photo_file_name, presence: true

  belongs_to :user

  def self.to_slide_info
    order(created_at: :desc).map{|x|[x.photo.url, x.created_at.to_date, x.good]}.to_json
  end
end

app/models/movement.rb
class Movement < ApplicationRecord
  has_many :exercises, inverse_of: :movement
  accepts_nested_attributes_for :exercises, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # gem dependencies
  # devise
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # paperclip
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :workouts, inverse_of: :user, dependent: :destroy
  has_many :worksets, through: :workouts
  has_many :exercises, through: :worksets
  has_many :movements, through: :worksets
  has_many :meals, inverse_of: :user, dependent: :destroy
  has_many :journals, inverse_of: :user, dependent: :destroy
  accepts_nested_attributes_for :workouts, allow_destroy: true
  accepts_nested_attributes_for :journals, allow_destroy: true

end

app/models/workout.rb
class Workout < ApplicationRecord
  # properties
  belongs_to :user, optional: true
  has_many :worksets, inverse_of: :workout, dependent: :destroy
  has_many :exercises, through: :worksets
  has_many :movements, through: :worksets
  accepts_nested_attributes_for :worksets, allow_destroy: true

  before_save do |workout|
    workout.date.iso8601
  end

  # methods
  def self.most_recent(integer)
    order(created_at: :desc).limit(integer).to_json(include: :worksets)
  end

end

app/models/workset.rb
class Workset < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :workout, optional: true
  belongs_to :exercise, optional: true
  belongs_to :movement, optional: true

  validates :weight, numericality: { only_integer: true }, presence: true
  validates :reps, numericality: { only_integer: true }, presence: true
  validates :rpe, numericality: { only_integer: true, less_than_or_equal_to: 10 }, allow_blank: true

  def self.daily_maxes
    where(daily_max: true).joins(:workout, :exercise).select('exercises.name, worksets.weight, worksets.reps, worksets.rpe, workouts.date').to_json
  end

  def self.cumulative_volume
    order(:movement_id, :exercise_id, created_at: :desc).to_json
  end

  def self.rep_ranges
    order(:movement_id, :exercise_id).to_json
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception, prepend: true

end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController

  def volume
    @patterns = current_user.worksets.cumulative_volume

    respond_to do |format|
      format.html
      format.json { render json: @patterns }
    end
  end

  def intensity
    @maxes = current_user.worksets.daily_maxes

    respond_to do |format|
      format.html
      format.json { render json: @maxes }
    end
  end

  def rep_ranges
    @sets = current_user.worksets.rep_ranges

    respond_to do |format|
      format.html
      format.json { render json: @sets }
    end
  end

end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  def index
  end

  def show
    @journal = Journal.find_by_id(params[:id])
  end

  def new
    @journal = current_user.journals.new
  end

  def create
    @journal = current_user.journals.new(journal_params)
    @journal.user_id = current_user.id
    if @journal.save
      redirect_to @journal, notice: 'Success!'
    else
      render 'new', notice: 'Something Went Wrong'
    end
  end

  private

  def journal_params
    params.require(:journal).permit(:id, :user_id, :title, :entry)
  end

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def index
    @meal = Meal.first
  end


  def slides
    @meals = current_user.meals.to_slide_info
    respond_to do |format|
      format.html
      format.json { render json: @meals }
    end
  end

  def show
  end

  def new
    @meal = current_user.meals.new
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.user_id = current_user.id
    if @meal.save
      redirect_to current_user, notice: 'Success!'
    else
      render 'new', notice: 'Something Went Wrong'
    end
  end

  private

  def meal_params
    params.require(:meal).permit(:id, :user_id, :photo, :good, '_destroy')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
  end


  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user), notice: 'Updated your information'
    else
      render 'edit'
    end
  end

  def destroy
    current_user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :bio, :location, :age, :height, :weight, :avatar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end 
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  def new
    @workout = current_user.workouts.new
    @workout.worksets.new
  end

  def create
    @workout = current_user.workouts.new(workout_params)
    @workout.user_id = current_user.id
    if @workout.save
      redirect_to current_user, notice: 'Success!'
    else
      render 'new', notice: 'Something Went Wrong'
    end
  end

  private

  def workout_params
    params.require(:workout).permit(:id, :date, :user_id, '_destroy', worksets_attributes: [:id, :workout_id, :movement_id, :exercise_id, :weight, :reps, :rpe, '_destroy'])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/graphs_helper.rb
module GraphsHelper


end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/graphs/_intensity.html.erb
  <canvas id="dailyMaxes" width="300px" height="300px" ></canvas>

app/views/graphs/_rep_ranges.html.erb
<canvas id="rep-ranges" width="300px" height="300px"></canvas>

app/views/graphs/_volume.html.erb
<canvas id="accumVolume" width="300px" height="300px"></canvas>

app/views/graphs/index.html.erb
<canvas id="myChart"></canvas>

app/views/journals/_index.html.erb
<div id="notes-accordion">
  <% current_user.journals.each do |j| %>
  <div class="note-title">
    <td><%= j.title %></td>
  </div>
  <div class="note-contents hidden">
    <td><%= j.entry.html_safe %></td>
  </div>
  <% end %>
</div>

app/views/journals/new.html.erb
<div class="card-journal">
<%= simple_form_for @journal, url: journals_path(current_user) do |j| %>
<% if @journal.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@journals.errors.count, "error") %> prohibited this entry from being saved:</h2>
    <ul>
    <% @meal.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= j.input :title, placeholder: "Title",label: false %>
<%= j.input :entry, as: :trix_editor, class: "journal-entry", label: false %>
<%= j.button :submit, "Post" %>
<% end %>
</div>

app/views/journals/show.html.erb
  <h3><%= @journal.title.html_safe %></h3>
  <p><%= @journal.entry.html_safe %></p>

app/views/meals/_slides.html.erb
  <div id="meal-carousel">
    <div id="overlay"></div>
    <i id="prev" class="fa fa-chevron-left fa-3x"></i>
    <i id="next" class="fa fa-chevron-right fa-3x"></i>
    <div id="current"></div>
  </div>

app/views/meals/new.html.erb
<div id="meal-modal">
  <%= simple_form_for @meal, url: meals_path do |m| %>

  <% if @meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>
      <ul>
      <% @meal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
      <i class="fa fa-camera fa-2x" id="meal-photo"></i>
      <%= m.input :photo, as: :file, input_html: {id: "file-button", hidden: true}, label: false %>
      <span>
        <h3>Is this good for you?</h3>
        <%= m.input :good, as: :boolean, input_html: {class: "checkbox"}, label: false %>
      </span>
      <%= m.button :submit, input_html: {class: "fa fa-plus-circle fa-2x"}, label: false %>
  <% end %>
</div>

app/views/meals/show.html.erb
<h1>Meals#show</h1>
<p>Find me in app/views/meals/show.html.erb</p>

app/views/users/edit.html.erb
<%= simple_form_for current_user do |f| %>
<div class="card-show">
  <%= f.input :avatar, input_html: {class: 'form-input'}, label: false %>
  <%= f.input :username, placeholder: 'username', input_html: {class: 'form-input'}, label: false %>
  <%= f.input :location, placeholder: 'location', input_html: {class: 'form-input'}, label: false %>
  <%= f.input :age, placeholder: 'age', input_html: {class: 'form-input'}, label: false %>
  <%= link_to "Edit Account", edit_user_registration_path(current_user) %><br>
  <%= f.submit %>
</div>

<% end %>

app/views/users/show.html.erb
<div class="card-show">
    <%= render 'graphs/intensity' %>
</div>

<div class="card-show">
    <%= render 'graphs/volume' %>
</div>

<div class="card-show">
    <%= render 'graphs/rep_ranges' %>
</div>

<div class="card-show">
    <%= render 'meals/slides' %>
</div>

<div class="card-show">
    <%= render 'journals/index' %>
</div>

app/views/welcome/index.html.erb
<h1>Hello World</h1>
<div id='box'></div>

app/views/workouts/_exercise_fields.html.erb
<div class='nested-fields form-fields'>
  <div class="remove">
    <%= link_to_remove_association "X", f, input_html: {} %>
  </div>

  <div class="movement">
    <%= f.input :pattern, collection: Exercise.order(:pattern).pluck(:pattern).uniq, input_html: {class: 'form-input pattern-fields'}, label: false %>
  </div>

  <div class="exercise">
    <%= f.input :name, collection: Exercise.group(:pattern, :name), input_html: {class: 'form-input exercise-fields'}, label: false %>
  </div>

  <div class="weight">
    <%= f.input :weight, placeholder: 'Weight', input_html: {class: 'form-input weight-fields'}, label: false %>
  </div>

  <div class="reps">
    <%= f.input :reps, placeholder: 'Reps', input_html: {class: 'form-input rep-fields'}, label: false %>
  </div>

  <div class="intensity">
    <%= f.input :rpe, placeholder: 'RPE', input_html: {class: 'form-input intensity-fields'}, label: false %>
  </div>


</div>

app/views/workouts/_workset_fields.html.erb
<div class='nested-fields form-fields'>
  <div class="remove">
    <%= link_to_remove_association "X", f %>
  </div>

  <div class="movement">
    <%= f.input :movement_id, collection: Movement.order(:created_at), label_method: "pattern", input_html: {class: 'form-input pattern-fields'}, label: false %>
  </div>

  <div class="exercise">
    <%= f.input :exercise_id, collection: Movement.order(:pattern), as: :grouped_select, group_method: :exercises, group_label_method: :pattern, input_html: {class: 'form-input exercise-fields'}, label: false %>
  </div>

  <div class="weight">
    <%= f.input :weight, placeholder: 'Weight', input_html: {class: 'form-input weight-fields'}, label: false %>
  </div>

  <div class="reps">
    <%= f.input :reps, placeholder: 'Reps', input_html: {class: 'form-input rep-fields'}, label: false %>
  </div>

  <div class="intensity">
    <%= f.input :rpe, placeholder: 'RPE', input_html: {class: 'form-input intensity-fields'}, label: false %>
  </div>


</div>

app/views/workouts/new.html.erb
<div class="card-workout">

  <%= simple_form_for @workout do |f| %>

  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>
      <ul>
      <% @workout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :date, as: :date, input_html: {id: 'session-info'}, html5: true, label: false %>
    <%= f.simple_fields_for :worksets do |workset| %>
      <%= render 'workset_fields', f: workset %>
    <% end %>

    <div class="links">
      <%= link_to_add_association '', f, :worksets, id: 'add-set' %>
    </div>
      <%= f.button :submit, "", id: 'finish' %>
  <% end %>
</div>